version: 2

project_name: fleetd

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - buf generate

builds:
  - id: fleetctl
    main: ./cmd/fleetctl
    binary: fleetctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X fleetd.sh/internal/version.Version={{.Version}}
      - -X fleetd.sh/internal/version.CommitSHA={{.Commit}}
      - -X fleetd.sh/internal/version.BuildTime={{.Date}}

  - id: fleetd
    main: ./cmd/fleetd
    binary: fleetd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X fleetd.sh/internal/version.Version={{.Version}}
      - -X fleetd.sh/internal/version.CommitSHA={{.Commit}}
      - -X fleetd.sh/internal/version.BuildTime={{.Date}}

  - id: device-api
    main: ./cmd/device-api
    binary: device-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X fleetd.sh/internal/version.Version={{.Version}}
      - -X fleetd.sh/internal/version.CommitSHA={{.Commit}}
      - -X fleetd.sh/internal/version.BuildTime={{.Date}}

  - id: platform-api
    main: ./cmd/platform-api
    binary: platform-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X fleetd.sh/internal/version.Version={{.Version}}
      - -X fleetd.sh/internal/version.CommitSHA={{.Commit}}
      - -X fleetd.sh/internal/version.BuildTime={{.Date}}

archives:
  - id: fleetctl
    rlcp: true
    name_template: "fleetctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

  - id: fleetd
    rlcp: true
    name_template: "fleetd_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - QUICK_START.md

  - id: servers
    rlcp: true
    name_template: "fleetd-servers_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Code Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Security Updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: fleetd-sh
    name: fleetd
  draft: false
  prerelease: auto
  mode: keep-existing
  name_template: "{{.ProjectName}}-v{{.Version}}"
  extra_files:
    - glob: scripts/install.sh
      name_template: install.sh

dockers_v2:
  - id: device-api
    ids:
      - device-api
    image_templates:
      - "ghcr.io/fleetd-sh/device-api:latest"
      - "ghcr.io/fleetd-sh/device-api:{{ .Tag }}"
      - "ghcr.io/fleetd-sh/device-api:{{ .Major }}"
      - "ghcr.io/fleetd-sh/device-api:{{ .Major }}.{{ .Minor }}"
    dockerfile: container/device.dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=device-api"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - id: platform-api
    ids:
      - platform-api
    image_templates:
      - "ghcr.io/fleetd-sh/platform-api:latest"
      - "ghcr.io/fleetd-sh/platform-api:{{ .Tag }}"
      - "ghcr.io/fleetd-sh/platform-api:{{ .Major }}"
      - "ghcr.io/fleetd-sh/platform-api:{{ .Major }}.{{ .Minor }}"
    dockerfile: container/platform.dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=platform-api"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - id: fleetd
    ids:
      - fleetd
    image_templates:
      - "ghcr.io/fleetd-sh/fleetd:latest"
      - "ghcr.io/fleetd-sh/fleetd:{{ .Tag }}"
      - "ghcr.io/fleetd-sh/fleetd:{{ .Major }}"
      - "ghcr.io/fleetd-sh/fleetd:{{ .Major }}.{{ .Minor }}"
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64,linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=fleetd"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

homebrew:
  - name: fleetctl
    ids:
      - fleetctl
    repository:
      owner: fleetd-sh
      name: homebrew-fleetd
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@fleetd.sh
    homepage: "https://fleetd.sh"
    description: "Fleet management CLI tool for edge device orchestration"
    license: "MIT"
    directory: Formula
    test: |
      system "#{bin}/fleetctl", "--version"
    install: |
      bin.install "fleetctl"

      # Install bash completions
      output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "bash")
      (bash_completion/"fleetctl").write output

      # Install zsh completions
      output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "zsh")
      (zsh_completion/"_fleetctl").write output

      # Install fish completions
      output = Utils.safe_popen_read("#{bin}/fleetctl", "completion", "fish")
      (fish_completion/"fleetctl.fish").write output

scoops:
  - repository:
      owner: fleetd-sh
      name: scoop-fleetd
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@fleetd.sh
    homepage: "https://fleetd.sh"
    description: "Fleet management CLI tool for edge device orchestration"
    license: MIT
    persist:
      - "data"
      - "config.toml"

nfpms:
  - id: fleetctl
    package_name: fleetctl
    vendor: fleetd
    homepage: https://fleetd.sh
    maintainer: fleetd maintainers <maintainers@fleetd.sh>
    description: Fleet management CLI tool for edge device orchestration
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - ca-certificates
    recommends:
      - git
    section: utils
    priority: optional
    contents:
      - src: LICENSE
        dst: /usr/share/doc/fleetctl/LICENSE
      - src: README.md
        dst: /usr/share/doc/fleetctl/README.md
    scripts:
      postinstall: |
        #!/bin/sh
        echo "fleetctl installed successfully"
        echo "Run 'fleetctl --help' to get started"

  - id: fleetd
    package_name: fleetd
    vendor: fleetd
    homepage: https://fleetd.sh
    maintainer: fleetd maintainers <maintainers@fleetd.sh>
    description: Fleet daemon for edge device management
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - ca-certificates
    section: admin
    priority: optional
    contents:
      - src: LICENSE
        dst: /usr/share/doc/fleetd/LICENSE
      - src: README.md
        dst: /usr/share/doc/fleetd/README.md
      - src: configs/fleetd.service
        dst: /etc/systemd/system/fleetd.service
        type: config
      - src: configs/fleetd.toml
        dst: /etc/fleetd/config.toml
        type: config
    scripts:
      postinstall: |
        #!/bin/sh
        systemctl daemon-reload
        echo "fleetd installed successfully"
        echo "Run 'systemctl start fleetd' to start the service"
      preremove: |
        #!/bin/sh
        systemctl stop fleetd || true
        systemctl disable fleetd || true

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"
    artifacts: all

sboms:
  - id: source
    artifacts: source
  - id: binaries
    artifacts: binary
  - id: archives
    artifacts: archive
  - id: packages
    artifacts: package

