# Fleet Project Configuration

[project]
id = "fleetd-dev"
name = "fleetd Development"

# Device API - High-volume device traffic (metrics, logs, telemetry, registration)
[device_api]
enabled = true
port = 8080
host = "localhost"
# Device API receives all device communications and routes data to backends

# Platform API - Management operations (CLI, Web UI, third-party integrations)
[platform_api]
enabled = true
port = 8090
host = "localhost"
# For remote deployment, you can use:
# host = "fleetd.molland.sh"  # Will use https:// automatically
# port = 443                   # Optional, defaults to 443 for https
# OR use a full URL:
# url = "https://fleetd.molland.sh"
# Platform API manages fleets, deployments, and analytics without being burdened by device traffic

[db]
port = 5432
host = "localhost"
name = "fleetd"
user = "fleetd"
# password = "" # Set via environment variable POSTGRES_PASSWORD for production

[stack]
# Services to start with 'fleet start'
services = [
  "postgres",
  "victoriametrics",
  "loki",
  "valkey",
  "traefik"
]

[gateway]
port = 80
dashboard_port = 8080

[telemetry]
victoria_metrics_port = 8428
loki_port = 3100
grafana_port = 3001

[auth]
# jwt_secret = "" # Set via environment variable JWT_SECRET for production
api_keys = []

[provisioning]
default_image = "raspios-lite"
default_user = "pi"

# Environment-specific overrides
[environments.staging]
device_api.url = "https://device-staging.fleetd.sh"
control_api.url = "https://api-staging.fleetd.sh"
db.host = "staging-db.fleetd.sh"

[environments.production]
device_api.url = "https://device.fleetd.sh"
control_api.url = "https://api.fleetd.sh"
db.host = "prod-db.fleetd.sh"