FROM alpine:latest

# Create required directories
RUN mkdir -p /var/lib/fleetd/state

# Copy the agent binary into the container
COPY fleetd /usr/local/bin/fleetd

# Make it executable
RUN chmod +x /usr/local/bin/fleetd

# Set the entrypoint to run the agent subcommand
ENTRYPOINT ["/usr/local/bin/fleetd", "agent"]

EXPOSE 8080