name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Install just
      uses: extractions/setup-just@v1
      with:
        just-version: '1.36'

    - name: Check formatting
      run: |
        if [ -n "$(go fmt ./...)" ]; then
          echo "Code is not formatted. Please run 'go fmt ./...'"
          exit 1
        fi

    - name: Verify dependencies
      run: go mod verify

    - name: Run vet
      run: go vet ./...

    - name: Install Docker
      uses: docker/setup-buildx-action@v3
      with:
        version: 'v0.9.1'

    - name: Run all tests
      env:
        INTEGRATION: 1
        DOCKER_API_VERSION: 1.45
      run: just test-all
