name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install web dependencies
        run: cd studio && bun install

      - name: Install just
        uses: extractions/setup-just@v1
        with:
          just-version: "1.36"

      - name: Check formatting
        run: |
          UNFORMATTED=$(go fmt ./...)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files are not formatted:"
            echo "$UNFORMATTED"
            echo "Please run 'go fmt ./...'"
            exit 1
          fi

      - name: Verify dependencies
        run: go mod verify

      - name: Run vet
        run: go vet ./...

      - name: Install Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: "v0.9.1"

      - name: Run all tests
        env:
          INTEGRATION: 1
          DOCKER_API_VERSION: 1.45
          CI: true
        run: just test-all
