name: Security Scanning

on:
  schedule:
    # Run security scans weekly on Mondays at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:

env:
  GO_VERSION: '1.23'
  NODE_VERSION: '24.9.0'

jobs:
  # Main security-tests job disabled until test/security framework is implemented
  # TODO: Re-enable when test/security tooling exists

  dependency-security:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Go vulnerability scan
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install studio dependencies
        run: |
          cd studio
          npm ci || bun install

      - name: Run npm audit
        run: |
          cd studio
          npm audit --audit-level moderate || true

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  container-security:
    name: Container Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: |
          docker build -f Dockerfile.device-api -t fleetd/device-api:test . || echo "device-api Dockerfile not found"
          docker build -f Dockerfile.platform-api -t fleetd/platform-api:test . || echo "platform-api Dockerfile not found"

      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: 'fleetd/device-api:test'
          format: 'sarif'
          output: 'trivy-container-results.sarif'

      - name: Upload container scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-container-results.sarif'

  security-baseline:
    name: Security Baseline Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for exposed secrets with gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
